name: PHP Linting

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: PHP Lint 5.5
        uses: PrestaShopCorp/github-action-php-lint/5.5@v2.3.1
      - name: PHP Lint 5.6
        uses: PrestaShopCorp/github-action-php-lint/5.6@v2.3.1
      - name: PHP Lint 7.1
        uses: PrestaShopCorp/github-action-php-lint/7.1@v2.3.1
      - name: PHP Lint 7.2
        uses: PrestaShopCorp/github-action-php-lint/7.2@v2.3.1
      - name: PHP Lint 7.3
        uses: PrestaShopCorp/github-action-php-lint/7.3@v2.3.1
      - name: PHP Lint 7.4
        uses: PrestaShopCorp/github-action-php-lint/7.4@v2.3.1
      - name: PHP Lint 8.0
        uses: PrestaShopCorp/github-action-php-lint/8.0@v2.3.1
      - name: PHP Lint 8.1
        uses: PrestaShopCorp/github-action-php-lint/8.1@v2.3.1
      - name: PHP Lint 8.2
        uses: PrestaShopCorp/github-action-php-lint/8.2@v2.3.1
      - name: PHP Lint 8.3
        uses: PrestaShopCorp/github-action-php-lint/8.3@v2.3.1
      - name: PHP Lint 8.4
        uses: PrestaShopCorp/github-action-php-lint/8.4@v2.3.1

on:
  push:
    branches:
      - main
      - stable
